const C=window.SYNERGY_CONFIG, API=C.API_URL;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={page:'today',dashboard:null,leads:[],courses:[],students:[],payments:[],expenses:[],followups:[],selectedLead:null};
const statusMap={new:'جدید',contacted:'تماس گرفته شد',interested:'علاقه‌مند',payment_info_sent:'شرایط ارسال شد',awaiting_payment:'منتظر پرداخت',paid:'پرداخت شد',registered:'ثبت‌نام قطعی',lost:'از دست رفته'};
const statusClass={new:'blue',contacted:'cyan',interested:'violet',payment_info_sent:'amber',awaiting_payment:'orange',paid:'green',registered:'emerald',lost:'red'};
const navItems=[['today','⌂','امروز'],['leads','◎','مشتریان'],['courses','▣','دوره‌ها'],['finance','◈','مالی'],['reports','▤','گزارش']];
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(v){return new Intl.NumberFormat('fa-IR').format(Number(v||0))+' '+C.CURRENCY}
function faNum(v){return new Intl.NumberFormat('fa-IR').format(Number(v||0))}
function dateFa(v){if(!v)return '—';try{return new Intl.DateTimeFormat('fa-IR',{month:'short',day:'numeric'}).format(new Date(v))}catch{return v}}
function toast(msg,bad=false){const t=$('#toast');t.textContent=msg;t.className=bad?'show bad':'show';setTimeout(()=>t.className='',2800)}
function loading(v){$('#loading').classList.toggle('hidden',!v)}
async function get(action){const r=await fetch(`${API}?action=${encodeURIComponent(action)}&t=${Date.now()}`);if(!r.ok)throw Error('API '+r.status);return r.json()}
async function post(action,data){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,data})});if(!r.ok)throw Error('API '+r.status);return r.json()}
function setConnected(ok){$('#connectionDot').className=ok?'ok':'bad';$('#connectionText').textContent=ok?'Google Sheets متصل':'اتصال قطع است'}
async function loadAll(show=true){if(show)loading(true);try{const [d,l,c,s,p,e,f]=await Promise.all(['dashboard','leads','courses','students','payments','expenses','followups'].map(get));state.dashboard=d.data||{};state.leads=l.data||[];state.courses=c.data||[];state.students=s.data||[];state.payments=p.data||[];state.expenses=e.data||[];state.followups=f.data||[];setConnected(true);render()}catch(e){console.error(e);setConnected(false);toast('ارتباط با دیتابیس برقرار نشد',true);renderError()}finally{loading(false)}}
function initNav(){const html=navItems.map(([id,ic,tx])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span>${ic}</span>${tx}</button>`).join('');$('#nav').innerHTML=html;$('#bottomNav').innerHTML=navItems.slice(0,4).map(([id,ic,tx])=>`<button class="${state.page===id?'active':''}" data-page="${id}"><b>${ic}</b><span>${tx}</span></button>`).join('');$$('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;closeSide();initNav();render()})}
function render(){initNav();const pages={today:renderToday,leads:renderLeads,courses:renderCourses,finance:renderFinance,reports:renderReports};(pages[state.page]||renderToday)()}
function title(a,b){$('#pageTitle').textContent=a;$('#pageSub').textContent=b}
function renderToday(){title('امروز','مرکز عملیات روزانه آکادمی');const d=state.dashboard||{},today=d.today_followups||[],over=d.overdue_followups||[],waiting=state.leads.filter(x=>x.status==='awaiting_payment');$('#content').innerHTML=`<section class="hero"><div><span class="eyebrow">SYNERGY ACADEMY</span><h1>صبح بخیر؛ امروز چه چیزی نیاز به توجه دارد؟</h1><p>${faNum(today.length)} پیگیری امروز و ${faNum(over.length)} پیگیری عقب‌افتاده دارید.</p></div><button data-action="newLead" class="hero-add">+ ثبت متقاضی</button></section><div class="kpi-grid"><div class="kpi"><span>کل متقاضیان</span><strong>${faNum(d.total_leads)}</strong><small>CRM</small></div><div class="kpi warning"><span>پیگیری امروز</span><strong>${faNum(today.length)}</strong><small>نیازمند اقدام</small></div><div class="kpi danger"><span>عقب‌افتاده</span><strong>${faNum(over.length)}</strong><small>اولویت بالا</small></div><div class="kpi success"><span>نرخ تبدیل</span><strong>${faNum(d.conversion_rate)}٪</strong><small>ثبت‌نام قطعی</small></div></div><div class="two-col"><section class="panel"><div class="panel-head"><div><h3>کارهای امروز</h3><p>پیگیری‌هایی که باید انجام شوند</p></div><span class="count">${faNum(today.length+over.length)}</span></div>${leadList([...over,...today].slice(0,8),true)}</section><section class="panel"><div class="panel-head"><div><h3>منتظر پرداخت</h3><p>فرصت‌های نزدیک به ثبت‌نام</p></div><span class="count">${faNum(waiting.length)}</span></div>${leadList(waiting.slice(0,8),false)}</section></div><section class="panel finance-strip"><div><span>درآمد تأییدشده</span><strong>${money(d.revenue)}</strong></div><div><span>هزینه</span><strong>${money(d.expenses)}</strong></div><div><span>سود</span><strong>${money(d.profit)}</strong></div></section>`;bindActions()}
function leadList(arr,follow){if(!arr.length)return `<div class="empty"><b>همه‌چیز مرتب است</b><span>موردی برای نمایش وجود ندارد.</span></div>`;return `<div class="lead-list">${arr.map(x=>`<button class="lead-row" data-lead="${esc(x.lead_id)}"><div class="avatar">${esc((x.full_name||'?').trim()[0])}</div><div class="lead-main"><b>${esc(x.full_name)}</b><span>${esc(x.mobile)}${x.course_id?' · '+esc(courseName(x.course_id)):''}</span></div><div class="lead-end"><em class="badge ${statusClass[x.status]||'gray'}">${statusMap[x.status]||esc(x.status)}</em>${follow?`<small>${dateFa(x.next_followup)}</small>`:''}</div></button>`).join('')}</div>`}
function renderLeads(){title('مشتریان','Pipeline فروش و پیگیری متقاضیان');const groups=Object.keys(statusMap);$('#content').innerHTML=`<div class="toolbar"><div class="search"><span>⌕</span><input id="leadSearch" placeholder="جستجو نام یا موبایل..."></div><button class="primary" data-action="newLead">+ مشتری جدید</button></div><div class="pipeline">${groups.map(st=>{const a=state.leads.filter(x=>x.status===st);return `<section class="pipe"><div class="pipe-head"><span class="dot ${statusClass[st]}"></span><b>${statusMap[st]}</b><em>${faNum(a.length)}</em></div><div class="pipe-body">${a.map(leadCard).join('')||'<div class="pipe-empty">موردی نیست</div>'}</div></section>`}).join('')}</div><section class="panel mobile-leads"><div id="mobileLeadList">${leadList(state.leads,false)}</div></section>`;$('#leadSearch').oninput=e=>{const q=e.target.value.trim();const a=state.leads.filter(x=>(x.full_name+x.mobile).includes(q));$('#mobileLeadList').innerHTML=leadList(a,false);bindLeadClicks()};bindActions()}
function leadCard(x){return `<button class="lead-card" data-lead="${esc(x.lead_id)}"><div><b>${esc(x.full_name)}</b><span>${esc(x.mobile)}</span></div><p>${esc(courseName(x.course_id)||'دوره مشخص نشده')}</p><footer><small>${esc(x.source||'—')}</small><small>${x.next_followup?dateFa(x.next_followup):'بدون پیگیری'}</small></footer></button>`}
function courseName(id){return (state.courses.find(x=>String(x.course_id)===String(id))||{}).course_name||id||''}
function renderCourses(){title('دوره‌ها','مدیریت دوره‌های آموزشی');$('#content').innerHTML=`<div class="toolbar"><div><h3>دوره‌های آکادمی</h3><p>${faNum(state.courses.length)} دوره ثبت شده</p></div><button class="primary" data-action="newCourse">+ دوره جدید</button></div><div class="course-grid">${state.courses.map(c=>`<article class="course-card"><div class="course-top"><span class="badge ${c.status==='active'?'green':'gray'}">${c.status==='active'?'فعال':esc(c.status||'پیش‌نویس')}</span><small>${esc(c.course_code||'')}</small></div><h3>${esc(c.course_name)}</h3><p>${esc(c.partner_university||'دانشگاه همکار مشخص نشده')}</p><div class="course-meta"><span>ظرفیت <b>${faNum(c.capacity)}</b></span><span>قیمت <b>${money(c.standard_price)}</b></span></div><footer>${dateFa(c.start_date)} · ${esc(c.location||'—')}</footer></article>`).join('')||'<div class="empty wide"><b>هنوز دوره‌ای تعریف نشده</b><span>اولین دوره آکادمی را ایجاد کنید.</span></div>'}</div>`;bindActions()}
function renderFinance(){title('مالی','پرداخت‌ها، هزینه‌ها و سودآوری');const d=state.dashboard||{};$('#content').innerHTML=`<div class="kpi-grid"><div class="kpi success"><span>درآمد تأییدشده</span><strong class="money-kpi">${money(d.revenue)}</strong></div><div class="kpi danger"><span>کل هزینه</span><strong class="money-kpi">${money(d.expenses)}</strong></div><div class="kpi"><span>سود خالص</span><strong class="money-kpi">${money(d.profit)}</strong></div></div><div class="two-col"><section class="panel"><div class="panel-head"><div><h3>آخرین پرداخت‌ها</h3><p>تراکنش‌های ثبت‌شده</p></div><button class="text-btn" data-action="newPayment">+ پرداخت</button></div>${simpleRows(state.payments.slice(-8).reverse(),'payment')}</section><section class="panel"><div class="panel-head"><div><h3>آخرین هزینه‌ها</h3><p>هزینه‌های عملیاتی</p></div><button class="text-btn" data-action="newExpense">+ هزینه</button></div>${simpleRows(state.expenses.slice(-8).reverse(),'expense')}</section></div>`;bindActions()}
function simpleRows(a,type){if(!a.length)return '<div class="empty"><b>هنوز داده‌ای نیست</b><span>اولین رکورد را ثبت کنید.</span></div>';return `<div class="simple-list">${a.map(x=>`<div><span><b>${esc(type==='payment'?(courseName(x.course_id)||x.student_id||x.lead_id||'پرداخت'):(x.description||x.category||'هزینه'))}</b><small>${dateFa(type==='payment'?x.payment_date:x.expense_date)}</small></span><strong>${money(x.amount)}</strong></div>`).join('')}</div>`}
function renderReports(){title('گزارش مدیریت','نمای مدیریتی عملکرد آکادمی');const d=state.dashboard||{};$('#content').innerHTML=`<section class="board-hero"><span>BOARD VIEW</span><h1>${money(d.profit)}</h1><p>سود خالص ثبت‌شده آکادمی</p></section><div class="report-grid"><article><span>متقاضی</span><strong>${faNum(d.total_leads)}</strong></article><article><span>ثبت‌نام قطعی</span><strong>${faNum(d.registered_students)}</strong></article><article><span>نرخ تبدیل</span><strong>${faNum(d.conversion_rate)}٪</strong></article><article><span>دوره فعال</span><strong>${faNum(d.active_courses)}</strong></article></div><section class="panel"><div class="panel-head"><div><h3>قیف فروش</h3><p>تعداد مشتری در هر مرحله</p></div></div><div class="funnel">${Object.keys(statusMap).map(s=>`<div><span>${statusMap[s]}</span><b>${faNum(state.leads.filter(x=>x.status===s).length)}</b><i style="width:${Math.max(3,state.leads.length?state.leads.filter(x=>x.status===s).length/state.leads.length*100:0)}%"></i></div>`).join('')}</div></section>`}
function renderError(){$('#content').innerHTML='<div class="fatal"><b>ارتباط با Google Sheets برقرار نشد</b><span>اینترنت و Web App را بررسی کنید و دوباره تلاش کنید.</span><button id="retry" class="primary">تلاش مجدد</button></div>';$('#retry').onclick=()=>loadAll()}
function bindActions(){$$('[data-action]').forEach(b=>b.onclick=()=>openAction(b.dataset.action));bindLeadClicks()}
function bindLeadClicks(){$$('[data-lead]').forEach(b=>b.onclick=()=>openLead(b.dataset.lead))}
function modal(html){$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden')}
function closeModal(){$('#modal').classList.add('hidden');state.selectedLead=null}
function formField(label,name,type='text',extra=''){return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" ${extra}></label>`}
function selectField(label,name,opts){return `<label class="field"><span>${label}</span><select name="${name}">${opts}</select></label>`}
function openAction(a){if(a==='newLead')return newLead();if(a==='newCourse')return newCourse();if(a==='newExpense')return newExpense();if(a==='newPayment')return newPayment()}
function newLead(){modal(`<div class="modal-title"><span>مشتری جدید</span><h2>ثبت متقاضی دوره</h2><p>اطلاعات اولیه را وارد کنید؛ بقیه مسیر در پرونده مشتری تکمیل می‌شود.</p></div><form id="leadForm" class="form-grid">${formField('نام و نام خانوادگی','full_name','text','required')}${formField('شماره موبایل','mobile','tel','required inputmode="tel"')}${selectField('دوره موردنظر','course_id','<option value="">انتخاب دوره</option>'+state.courses.map(c=>`<option value="${esc(c.course_id)}">${esc(c.course_name)}</option>`).join(''))}${selectField('منبع آشنایی','source','<option>Instagram</option><option>Telegram</option><option>University</option><option>Referral</option><option>Website</option><option>Other</option>')}${formField('پیگیری بعدی','next_followup','datetime-local')}${formField('مبلغ مورد انتظار','expected_amount','number','inputmode="numeric"')}<label class="field full"><span>یادداشت اولیه</span><textarea name="notes" rows="3"></textarea></label><button class="primary full submit" type="submit">ثبت مشتری</button></form>`);$('#leadForm').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));await submitPost('createLead',data,'مشتری ثبت شد')}}
function newCourse(){modal(`<div class="modal-title"><span>COURSE</span><h2>دوره جدید</h2></div><form id="courseForm" class="form-grid">${formField('نام دوره','course_name','text','required')}${formField('کد دوره','course_code')}${formField('دانشگاه همکار','partner_university')}${formField('مدرس','instructor')}${formField('تاریخ شروع','start_date','date')}${formField('محل برگزاری','location')}${formField('ظرفیت','capacity','number')}${formField('قیمت','standard_price','number')}<input type="hidden" name="status" value="active"><button class="primary full submit">ایجاد دوره</button></form>`);$('#courseForm').onsubmit=async e=>{e.preventDefault();await submitPost('createCourse',Object.fromEntries(new FormData(e.target)),'دوره ایجاد شد')}}
function newExpense(){modal(`<div class="modal-title"><span>EXPENSE</span><h2>ثبت هزینه</h2></div><form id="expenseForm" class="form-grid">${selectField('دوره','course_id','<option value="">عمومی آکادمی</option>'+state.courses.map(c=>`<option value="${esc(c.course_id)}">${esc(c.course_name)}</option>`).join(''))}${formField('تاریخ','expense_date','date','required')}${selectField('دسته هزینه','category','<option>مدرس</option><option>دانشگاه</option><option>تبلیغات</option><option>تجهیزات</option><option>پذیرایی</option><option>چاپ</option><option>سایر</option>')}${formField('مبلغ','amount','number','required')}${formField('شرح','description')}${formField('فروشنده/دریافت‌کننده','vendor')}<button class="primary full submit">ثبت هزینه</button></form>`);$('#expenseForm').onsubmit=async e=>{e.preventDefault();await submitPost('createExpense',Object.fromEntries(new FormData(e.target)),'هزینه ثبت شد')}}
function newPayment(lead=null){modal(`<div class="modal-title"><span>PAYMENT</span><h2>ثبت پرداخت</h2></div><form id="paymentForm" class="form-grid"><input type="hidden" name="lead_id" value="${esc(lead?.lead_id||'')}">${selectField('دوره','course_id','<option value="">انتخاب</option>'+state.courses.map(c=>`<option ${lead?.course_id===c.course_id?'selected':''} value="${esc(c.course_id)}">${esc(c.course_name)}</option>`).join(''))}${formField('مبلغ','amount','number','required')}${formField('تاریخ پرداخت','payment_date','date','required')}${selectField('روش پرداخت','payment_method','<option>کارت به کارت</option><option>انتقال بانکی</option><option>نقدی</option><option>POS</option>')}${formField('شماره پیگیری','transaction_reference')}<input type="hidden" name="status" value="approved"><button class="primary full submit">ثبت پرداخت</button></form>`);$('#paymentForm').onsubmit=async e=>{e.preventDefault();await submitPost('createPayment',Object.fromEntries(new FormData(e.target)),'پرداخت ثبت شد')}}
async function submitPost(action,data,msg){const btn=$('.submit');if(btn){btn.disabled=true;btn.textContent='در حال ثبت...'}try{const r=await post(action,data);if(!r.success)throw Error(r.message||'خطا');toast(msg);closeModal();await loadAll(false)}catch(e){toast(e.message||'ثبت انجام نشد',true);if(btn){btn.disabled=false;btn.textContent='تلاش مجدد'}}}
function openLead(id){const l=state.leads.find(x=>String(x.lead_id)===String(id));if(!l)return;state.selectedLead=l;const history=state.followups.filter(x=>String(x.lead_id)===String(id)).reverse();modal(`<div class="profile-head"><div class="avatar xl">${esc((l.full_name||'?')[0])}</div><div><span class="badge ${statusClass[l.status]||'gray'}">${statusMap[l.status]||l.status}</span><h2>${esc(l.full_name)}</h2><a href="tel:${esc(l.mobile)}">${esc(l.mobile)}</a></div></div><div class="quick-actions"><a href="tel:${esc(l.mobile)}">☎ تماس</a><a href="sms:${esc(l.mobile)}">✉ پیام</a><button id="followBtn">＋ ثبت پیگیری</button></div><div class="profile-info"><div><span>دوره</span><b>${esc(courseName(l.course_id)||'—')}</b></div><div><span>منبع</span><b>${esc(l.source||'—')}</b></div><div><span>پیگیری بعدی</span><b>${dateFa(l.next_followup)}</b></div><div><span>مبلغ مورد انتظار</span><b>${money(l.expected_amount)}</b></div></div><div class="profile-actions"><button id="payBtn" class="secondary">ثبت پرداخت</button>${l.status!=='registered'?'<button id="convertBtn" class="primary">تبدیل به دانشجو</button>':''}</div><section class="timeline"><h3>تاریخچه ارتباط</h3>${history.length?history.map(h=>`<div class="timeline-item"><i></i><div><b>${esc(h.result||statusMap[h.new_status]||'پیگیری')}</b><p>${esc(h.notes||'')}</p><small>${dateFa(h.created_at)} · ${esc(h.type||'')}</small></div></div>`).join(''):'<div class="empty"><span>هنوز پیگیری ثبت نشده است.</span></div>'}</section>`);$('#followBtn').onclick=()=>followForm(l);$('#payBtn').onclick=()=>newPayment(l);if($('#convertBtn'))$('#convertBtn').onclick=()=>convertLead(l)}
function followForm(l){modal(`<div class="modal-title"><span>FOLLOW-UP</span><h2>${esc(l.full_name)}</h2><p>نتیجه تماس یا پیام را ثبت کنید.</p></div><form id="followForm" class="form-grid"><input type="hidden" name="lead_id" value="${esc(l.lead_id)}">${selectField('نوع ارتباط','type','<option value="call">تماس</option><option value="message">پیام</option><option value="whatsapp">واتساپ</option><option value="in_person">حضوری</option>')}${selectField('مرحله جدید','new_status',Object.keys(statusMap).map(s=>`<option ${s===l.status?'selected':''} value="${s}">${statusMap[s]}</option>`).join(''))}${formField('نتیجه','result','text','required')}${formField('پیگیری بعدی','next_followup','datetime-local')}<label class="field full"><span>یادداشت</span><textarea name="notes" rows="4"></textarea></label><button class="primary full submit">ثبت پیگیری</button></form>`);$('#followForm').onsubmit=async e=>{e.preventDefault();await submitPost('addFollowUp',Object.fromEntries(new FormData(e.target)),'پیگیری ثبت شد')}}
async function convertLead(l){if(!confirm('این مشتری به عنوان دانشجو ثبت شود؟'))return;try{loading(true);const r=await post('convertLead',{lead_id:l.lead_id});if(!r.success)throw Error(r.message);toast('دانشجو با موفقیت ثبت شد');closeModal();await loadAll(false)}catch(e){toast(e.message,true)}finally{loading(false)}}
function closeSide(){$('.sidebar').classList.remove('open');$('#mobileScrim').classList.remove('show')}
$('#menuBtn').onclick=()=>{$('.sidebar').classList.add('open');$('#mobileScrim').classList.add('show')};$('#mobileScrim').onclick=closeSide;$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#refreshBtn').onclick=()=>loadAll();$('#today').textContent=new Intl.DateTimeFormat('fa-IR',{weekday:'long',day:'numeric',month:'long'}).format(new Date());document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a)openAction(a.dataset.action)});initNav();loadAll();
